name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build App
       run: bash build.sh
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            for IPA in *.ipa; do
            git add "$IPA"
            done
            git commit -m "Built App"
            git push
